# -*- coding: utf-8 -*-
class CreatePlanoDeSaudes < ActiveRecord::Migration
  def change
    create_table :plano_de_saudes do |t|
      t.string :nome
      t.string :slug

      t.timestamps
    end
    
    add_index :plano_de_saudes, :slug, :unique => true
    
    PlanoDeSaude.create(:nome => 'Allianz Saúde')
    PlanoDeSaude.create(:nome => 'Alvorecer')
    PlanoDeSaude.create(:nome => 'Ameplan')
    PlanoDeSaude.create(:nome => 'Amil')
    PlanoDeSaude.create(:nome => 'Ana Costa')
    PlanoDeSaude.create(:nome => 'APPAI')
    PlanoDeSaude.create(:nome => 'Bradesco Saúde')
    PlanoDeSaude.create(:nome => 'Brasilsaude')
    PlanoDeSaude.create(:nome => 'CABERGS')
    PlanoDeSaude.create(:nome => 'CABESP')
    PlanoDeSaude.create(:nome => 'Caixa de Assistência dos Advogados (OAB – RS)')
    PlanoDeSaude.create(:nome => 'Caixa de Assistência dos Advogados SP (CAASP)')
    PlanoDeSaude.create(:nome => 'Caixa Econômica Federal')
    PlanoDeSaude.create(:nome => 'CAMED')
    PlanoDeSaude.create(:nome => 'CAPESESP')
    PlanoDeSaude.create(:nome => 'Cassi Banco do Brasil')
    PlanoDeSaude.create(:nome => 'Centro Clínico Gaúcho')
    PlanoDeSaude.create(:nome => 'Cia. Vale do Rio Doce')
    PlanoDeSaude.create(:nome => 'Concard')
    PlanoDeSaude.create(:nome => 'Coopmil')
    PlanoDeSaude.create(:nome => 'Correios')
    PlanoDeSaude.create(:nome => 'Dix-Amico')
    PlanoDeSaude.create(:nome => 'Eletros-Saúde')
    PlanoDeSaude.create(:nome => 'Excelsior Med')
    PlanoDeSaude.create(:nome => 'Fundação Cesp')
    PlanoDeSaude.create(:nome => 'Fundação Saúde Itaú')
    PlanoDeSaude.create(:nome => 'Fundação São Francisco Xavier')
    PlanoDeSaude.create(:nome => 'Fundação Waldemar Barnsley Pessoa')
    PlanoDeSaude.create(:nome => 'Gama Saúde')
    PlanoDeSaude.create(:nome => 'Geap')
    PlanoDeSaude.create(:nome => 'Gebram Seguros')
    PlanoDeSaude.create(:nome => 'Golden Cross')
    PlanoDeSaude.create(:nome => 'Green Line')
    PlanoDeSaude.create(:nome => 'Grupo Hospitalar do Rio de Janeiro')
    PlanoDeSaude.create(:nome => 'Hapvida')
    PlanoDeSaude.create(:nome => 'Intermédica')
    PlanoDeSaude.create(:nome => 'IPE-Saúde')
    PlanoDeSaude.create(:nome => 'Irmandade da Santa Casa da Misericórdia')
    PlanoDeSaude.create(:nome => 'Justiça Federal')
    PlanoDeSaude.create(:nome => 'LINCX – Serviços de Saúde')
    PlanoDeSaude.create(:nome => 'Marítima')
    PlanoDeSaude.create(:nome => 'Medial Saúde')
    PlanoDeSaude.create(:nome => 'Mediservice')
    PlanoDeSaude.create(:nome => 'Metrus Saúde')
    PlanoDeSaude.create(:nome => 'Nimed Nordeste')
    PlanoDeSaude.create(:nome => 'Notre Dame')
    PlanoDeSaude.create(:nome => 'Omint')
    PlanoDeSaude.create(:nome => 'PASBC – Banco Central do Brasil')
    PlanoDeSaude.create(:nome => 'Petrobras AMS')
    PlanoDeSaude.create(:nome => 'Porto Seguro Saúde')
    PlanoDeSaude.create(:nome => 'Prodesp')
    PlanoDeSaude.create(:nome => 'Promed')
    PlanoDeSaude.create(:nome => 'Pró-Saúde')
    PlanoDeSaude.create(:nome => 'Sabesprev')
    PlanoDeSaude.create(:nome => 'Sametrade')
    PlanoDeSaude.create(:nome => 'Santa Helena')
    PlanoDeSaude.create(:nome => 'Santamalia Saúde')
    PlanoDeSaude.create(:nome => 'Seisa')
    PlanoDeSaude.create(:nome => 'Semeg Saúde')
    PlanoDeSaude.create(:nome => 'Sindicato dos Servidores Públicos')
    PlanoDeSaude.create(:nome => 'Sobam')
    PlanoDeSaude.create(:nome => 'Sul América Saúde')
    PlanoDeSaude.create(:nome => 'Tempo Saúde')
    PlanoDeSaude.create(:nome => 'Unibanco Saúde')
    PlanoDeSaude.create(:nome => 'Unimed')
    PlanoDeSaude.create(:nome => 'Unimed Belém')
    PlanoDeSaude.create(:nome => 'Unimed Bh')
    PlanoDeSaude.create(:nome => 'Unimed Campinas')
    PlanoDeSaude.create(:nome => 'Unimed Cuiabá')
    PlanoDeSaude.create(:nome => 'Unimed Curitiba')
    PlanoDeSaude.create(:nome => 'Unimed de Londrina')
    PlanoDeSaude.create(:nome => 'Unimed Florianópolis')
    PlanoDeSaude.create(:nome => 'Unimed Fortaleza')
    PlanoDeSaude.create(:nome => 'Unimed Goiania')
    PlanoDeSaude.create(:nome => 'Unimed João Pessoa')
    PlanoDeSaude.create(:nome => 'Unimed Londrina')
    PlanoDeSaude.create(:nome => 'Unimed Maceió')
    PlanoDeSaude.create(:nome => 'Unimed Manaus')
    PlanoDeSaude.create(:nome => 'Unimed Maringá')
    PlanoDeSaude.create(:nome => 'Unimed Natal')
    PlanoDeSaude.create(:nome => 'Unimed Paulistana')
    PlanoDeSaude.create(:nome => 'Unimed Porto Alegre')
    PlanoDeSaude.create(:nome => 'Unimed Recife')
    PlanoDeSaude.create(:nome => 'Unimed Ribeirao Preto')
    PlanoDeSaude.create(:nome => 'Unimed Santa Catarina')
    PlanoDeSaude.create(:nome => 'Unimed Sao José dos Campos')
    PlanoDeSaude.create(:nome => 'Unimed São Gonçalo / Niterói')
    PlanoDeSaude.create(:nome => 'Unimed São José do Rio Preto')
    PlanoDeSaude.create(:nome => 'Unimed São Paulo')
    PlanoDeSaude.create(:nome => 'Unimed Uberlândia')
    PlanoDeSaude.create(:nome => 'Unimed Vitória')
    PlanoDeSaude.create(:nome => 'Unimed-Rio')
    PlanoDeSaude.create(:nome => 'Uniodonto')
    PlanoDeSaude.create(:nome => 'Unoeste Saúde')
    PlanoDeSaude.create(:nome => 'Viccena')
    PlanoDeSaude.create(:nome => 'Vitallis Saúde')
  end
end
