# -*- coding: utf-8 -*-
class PopulaEspecialidades < ActiveRecord::Migration
  def up
    EspecialidadeMedica.create(:descricao => "acupuntura")
    EspecialidadeMedica.create(:descricao => "alergia e imunologia")
    EspecialidadeMedica.create(:descricao => "anestesiologia")
    EspecialidadeMedica.create(:descricao => "angiologia")
    EspecialidadeMedica.create(:descricao => "cancerologia")
    EspecialidadeMedica.create(:descricao => "cardiologia")
    EspecialidadeMedica.create(:descricao => "cirurgia cardiovascular")
    EspecialidadeMedica.create(:descricao => "cirurgia de cabeça e pescoço")
    EspecialidadeMedica.create(:descricao => "cirurgia do aparelho digestivo")
    EspecialidadeMedica.create(:descricao => "cirurgia geral")
    EspecialidadeMedica.create(:descricao => "cirurgia pediátrica")
    EspecialidadeMedica.create(:descricao => "cirurgia plástica")
    EspecialidadeMedica.create(:descricao => "cirurgia torácica")
    EspecialidadeMedica.create(:descricao => "cirurgia vascular")
    EspecialidadeMedica.create(:descricao => "clínica médica")
    EspecialidadeMedica.create(:descricao => "coloproctologia")
    EspecialidadeMedica.create(:descricao => "dermatologia")
    EspecialidadeMedica.create(:descricao => "endocrinologia")
    EspecialidadeMedica.create(:descricao => "endoscopia")
    EspecialidadeMedica.create(:descricao => "gastroenterologia")
    EspecialidadeMedica.create(:descricao => "genética médica")
    EspecialidadeMedica.create(:descricao => "geriatria")
    EspecialidadeMedica.create(:descricao => "ginecologia e obstetrícia")
    EspecialidadeMedica.create(:descricao => "hematologia e hemoterapia")
    EspecialidadeMedica.create(:descricao => "homeopatia")
    EspecialidadeMedica.create(:descricao => "infectologia")
    EspecialidadeMedica.create(:descricao => "mastologia")
    EspecialidadeMedica.create(:descricao => "medicina de família e comunidade")
    EspecialidadeMedica.create(:descricao => "medicina do trabalho")
    EspecialidadeMedica.create(:descricao => "medicina do tráfego")
    EspecialidadeMedica.create(:descricao => "medicina esportiva")
    EspecialidadeMedica.create(:descricao => "medicina física e reabilitação")
    EspecialidadeMedica.create(:descricao => "medicina intensiva")
    EspecialidadeMedica.create(:descricao => "medicina legal")
    EspecialidadeMedica.create(:descricao => "medicina nuclear")
    EspecialidadeMedica.create(:descricao => "medicina preventiva e social")
    EspecialidadeMedica.create(:descricao => "nefrologia")
    EspecialidadeMedica.create(:descricao => "neurocirurgia")
    EspecialidadeMedica.create(:descricao => "neurologia")
    EspecialidadeMedica.create(:descricao => "nutrologia")
    EspecialidadeMedica.create(:descricao => "oftalmologia")
    EspecialidadeMedica.create(:descricao => "ortopedia e traumatologia")
    EspecialidadeMedica.create(:descricao => "otorrinolaringologia")
    EspecialidadeMedica.create(:descricao => "patologia")
    EspecialidadeMedica.create(:descricao => "patologia clínica/medicina laboratorial")
    EspecialidadeMedica.create(:descricao => "pediatria")
    EspecialidadeMedica.create(:descricao => "pneumologia")
    EspecialidadeMedica.create(:descricao => "psiquiatria")
    EspecialidadeMedica.create(:descricao => "radiologia e diagnóstico por imagem")
    EspecialidadeMedica.create(:descricao => "radioterapia")
    EspecialidadeMedica.create(:descricao => "reumatologia")
    EspecialidadeMedica.create(:descricao => "urologia")


    AreaAtuacao.create(:descricao => "administração em saúde")
    AreaAtuacao.create(:descricao => "alergia e imunologia pediátrica")
    AreaAtuacao.create(:descricao => "angiorradiologia e cirurgia endovascular")
    AreaAtuacao.create(:descricao => "atendimento ao queimado")
    AreaAtuacao.create(:descricao => "cardiologia pediátrica")
    AreaAtuacao.create(:descricao => "cirurgia crânio-maxilo-facial")
    AreaAtuacao.create(:descricao => "cirurgia da coluna")
    AreaAtuacao.create(:descricao => "cirurgia da mão")
    AreaAtuacao.create(:descricao => "cirurgia dermatológica")
    AreaAtuacao.create(:descricao => "cirurgia do trauma")
    AreaAtuacao.create(:descricao => "cirurgia videolaparoscópica")
    AreaAtuacao.create(:descricao => "citopatologia")
    AreaAtuacao.create(:descricao => "cosmiatria")
    AreaAtuacao.create(:descricao => "dor")
    AreaAtuacao.create(:descricao => "ecocardiografia")
    AreaAtuacao.create(:descricao => "ecografia vascular com doppler")
    AreaAtuacao.create(:descricao => "eletrofisiologia clínica invasiva")
    AreaAtuacao.create(:descricao => "endocrinologia pediátrica")
    AreaAtuacao.create(:descricao => "endoscopia digestiva")
    AreaAtuacao.create(:descricao => "endoscopia ginecológica")
    AreaAtuacao.create(:descricao => "endoscopia respiratória")
    AreaAtuacao.create(:descricao => "ergometria")
    AreaAtuacao.create(:descricao => "foniatria")
    AreaAtuacao.create(:descricao => "gastroenterologia pediátrica")
    AreaAtuacao.create(:descricao => "hansenologia")
    AreaAtuacao.create(:descricao => "hematologia e hemoterapia pediátrica")
    AreaAtuacao.create(:descricao => "hemodinâmica e cardiologia intervencionista")
    AreaAtuacao.create(:descricao => "hepatologia")
    AreaAtuacao.create(:descricao => "infectologia hospitalar")
    AreaAtuacao.create(:descricao => "infectologia pediátrica")
    AreaAtuacao.create(:descricao => "medicina de urgência")
    AreaAtuacao.create(:descricao => "medicina do adolescente")
    AreaAtuacao.create(:descricao => "medicina fetal")
    AreaAtuacao.create(:descricao => "medicina intensiva neonatal")
    AreaAtuacao.create(:descricao => "medicina intensiva pediátrica")
    AreaAtuacao.create(:descricao => "nefrologia pediátrica")
    AreaAtuacao.create(:descricao => "neonatologia")
    AreaAtuacao.create(:descricao => "neurofisiologia clínica")
    AreaAtuacao.create(:descricao => "neurologia pediátrica")
    AreaAtuacao.create(:descricao => "neurorradiologia")
    AreaAtuacao.create(:descricao => "nutrição parenteral e enteral")
    AreaAtuacao.create(:descricao => "nutrição parenteral e enteral pediátrica")
    AreaAtuacao.create(:descricao => "nutrologia pediátrica")
    AreaAtuacao.create(:descricao => "pneumologia pediátrica")
    AreaAtuacao.create(:descricao => "psicogeriatria")
    AreaAtuacao.create(:descricao => "psicoterapia")
    AreaAtuacao.create(:descricao => "psiquiatria da infância e adolescência")
    AreaAtuacao.create(:descricao => "psiquiatria forense")
    AreaAtuacao.create(:descricao => "radiologia intervencionista e angiorradiologia")
    AreaAtuacao.create(:descricao => "reprodução humana")
    AreaAtuacao.create(:descricao => "reumatologia pediátrica")
    AreaAtuacao.create(:descricao => "sexologia")
    AreaAtuacao.create(:descricao => "ultra-sonografia em ginecologia e obstetrícia")

    # EspecialidadeMedica.find_each(&:save)
    # AreaAtuacao.find_each(&:save)
    
  end

  def down
    EspecialdiadeMedica.delete_all
    AreaAtuacao.delete_all
  end
end
